name: ${project.artifactId}
main: com.mcmiddleearth.guidebook.GuidebookPlugin
version: ${project.version}
description: sending information about places via chat messages
load: POSTWORLD
softdepend: [Multiverse-Core, worldedit-core, worldedit-bukkit, PluginUtils, bukkit, ProtocolLib, guava]
api-version: 1.15

commands:
    guidebook:
        description: manage guidebook areas
        
permissions:
    guidebook.staff:
        description: Gives access to all guidebook commands
        default: op
        children:
            autoteleport.user: true
    guidebook.user:
        description: gives access to /guidebook on and /guidebook off
        default: true
